[profile.default]
src = "src"
out = "out"
libs = ["lib"]
private_key = "${DEPLOYER_KEY}"
fs_permissions = [{ access = "read", path = "./config" }]

[rpc_endpoints]
# Ethereum
eth              = "https://1rpc.io/eth"
eth_test         = "https://1rpc.io/sepolia"

# BNB Smart Chain
bsc              = "https://1rpc.io/bnb"
bsc_test         = "https://bsc-testnet.drpc.org"

# EXPchain Testnet
exp_test         = "https://rpc1-testnet.expchain.ai"

polygon          = "https://polygon.drpc.org"
avalanche        = "https://1rpc.io/avax/c"
fantom           = "https://1rpc.io/ftm"
arbitrum_one     = "https://1rpc.io/arb"
arbitrum_nova    = "https://nova.arbitrum.io/rpc"
optimism         = "https://mainnet.optimism.io"
base             = "https://1rpc.io/base"
scroll           = "https://1rpc.io/scroll"
linea            = "https://1rpc.io/linea"
mantle           = "https://1rpc.io/mantle"
gnosis           = "https://1rpc.io/gnosis"
celo             = "https://1rpc.io/celo"
moonbeam         = "https://moonbeam.drpc.org"
metis            = "https://metis.drpc.org"
core             = "https://1rpc.io/core"
opbnb            = "https://1rpc.io/opbnb"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
